export const HUNT_CONFIG = Object.freeze({
    DEFAULT_MODE: 'CLASSIC',
    DEFAULT_RESPAWN_ENABLED: false,
    PLAYER_MAX_HP: 100,
    PLAYER_REGEN_PER_SECOND: 2.0,
    PLAYER_REGEN_DELAY: 3.0,
    SHIELD_MAX_HP: 40,
    COLLISION_DAMAGE: Object.freeze({
        WALL: 20,
        TRAIL: 28,
        PLAYER_CRASH: 40,
    }),
    MG: Object.freeze({
        DAMAGE: 8,
        COOLDOWN: 0.08,
        OVERHEAT_PER_SHOT: 7,
        COOLING_PER_SECOND: 24,
        LOCKOUT_THRESHOLD: 100,
        LOCKOUT_SECONDS: 1.2,
        RANGE: 95,
        MIN_FALLOFF: 0.5,
        AIM_DOT_MIN: 0.965,
        TRAIL_SAMPLE_STEP: 0.45,
        TRAIL_HIT_RADIUS: 0.78,
        TRAIL_SELF_SKIP_RECENT: 8,
        TRACER_BEAM_RADIUS: 0.16,
        TRACER_BULLET_RADIUS: 0.42,
    }),
    ROCKET: Object.freeze({
        VISUAL_SCALE_WEAK: 1.7,
        VISUAL_SCALE_MEDIUM: 1.95,
        VISUAL_SCALE_STRONG: 2.2,
        COLLISION_RADIUS_MULTIPLIER: 1.65,
        HOMING_TURN_RATE: 6.2,
        HOMING_LOCK_ON_ANGLE: 32,
        HOMING_REACQUIRE_INTERVAL: 0.12,
        HOMING_RANGE: 130,
    }),
    ROCKET_TIERS: Object.freeze({
        WEAK: Object.freeze({ damage: 15, spawnChance: 0.6 }),
        MEDIUM: Object.freeze({ damage: 35, spawnChance: 0.3 }),
        STRONG: Object.freeze({ damage: 60, spawnChance: 0.1 }),
    }),
    ROCKET_PICKUP_SPAWN_CHANCE: 0.4,
    TRAIL_SEGMENT_HP: 3,
    RESPAWN: Object.freeze({
        DELAY_SECONDS: 3.0,
        INVULNERABILITY_SECONDS: 1.0,
    }),
});
