export const MENU_TEXT_CATALOG = Object.freeze({
    'menu.level1.single.label': 'Single Player',
    'menu.level1.multiplayer.label': 'Multiplayer',
    'menu.level1.splitscreen.label': 'Splitscreen',
    'menu.level1.help.title': 'Ebene 1: Session-Typ',
    'menu.level1.help.next': 'Danach folgt Ebene 2 (Spielweg)',
    'menu.level2.title': 'Ebene 2: Spielweg',
    'menu.level2.quick.title': 'Schnellaktionen',
    'menu.level2.quick.hint': 'Diese Aktionen starten direkt ohne weiteren Menueschritt.',
    'menu.level2.quick_last.label': 'Letzte Einstellungen starten',
    'menu.level2.quick_random.label': 'Random Map starten',
    'menu.level2.mode.title': 'Modi',
    'menu.level2.mode.hint': 'Moduswahl befuellt Ebene 3 direkt mit sinnvollen Defaults.',
    'menu.level2.arcade.label': 'Arcade',
    'menu.level2.fight.label': 'Fight',
    'menu.level2.normal.label': 'Normal',
    'menu.level2.next_to_start.label': 'Weiter zu Ebene 3 (Start-Setup)',
    'menu.level3.title': 'Ebene 3: Start-Setup',
    'menu.level3.summary.title': 'Aktuelle Auswahl',
    'menu.level3.map.title': 'Map',
    'menu.level3.vehicle.title': 'Flugzeug',
    'menu.level3.theme.title': 'Hell / Dunkel (lokal)',
    'menu.level3.matchfields.title': 'Session-Relevante Matchfelder',
    'menu.level3.matchfields.hint': 'Regelset fuer die laufende Session waehlen.',
    'menu.level3.start.label': 'Starten',
    'menu.level3.open_level4.label': 'Ebene 4 oeffnen',
    'menu.level3.reset.label': 'Ebene 3 reset',
    'menu.level4.title': 'Ebene 4: Feineinstellungen & Tools',
    'menu.level4.reset.label': 'Ebene 4 reset',
    'menu.level4.close.label': 'Schliessen',
    'menu.level4.controls.title': 'Steuerung',
    'menu.level4.controls.reset_keys.label': 'Standard-Tasten wiederherstellen',
    'menu.level4.gameplay.title': 'Gameplay-Feineinstellungen',
    'menu.level4.advanced_map.title': 'Erweiterte Map-Einstellungen',
    'menu.level4.tools.title': 'Tools',
    'menu.level4.tools.profile_name.label': 'Profilname',
    'menu.level4.tools.profile_save.label': 'Profil speichern',
    'menu.level4.tools.profile_list.label': 'Gespeicherte Profile',
    'menu.level4.tools.profile_load.label': 'Profil laden',
    'menu.level4.tools.profile_delete.label': 'Profil loeschen',
    'menu.level4.tools.preset_catalog.label': 'Preset Katalog',
    'menu.level4.tools.preset_apply.label': 'Preset anwenden',
    'menu.level4.tools.preset_name.label': 'Neuer Preset-Name',
    'menu.level4.tools.preset_save_open.label': 'Als open preset speichern',
    'menu.level4.tools.preset_save_fixed.label': 'Als fixed preset speichern (owner)',
    'menu.level4.tools.preset_delete.label': 'Preset loeschen',
    'menu.level4.tools.map_editor.label': '3D Map-Editor oeffnen',
    'menu.level4.tools.vehicle_editor.label': 'Vehicle-Editor oeffnen',
    'menu.level4.tools.open_developer.label': 'Developer oeffnen',
    'menu.developer.title': 'Developer',
    'menu.developer.open_debug.label': 'Debug / Info oeffnen',
    'menu.developer.text_override.title': 'Textkatalog-Override',
    'menu.developer.text_override.apply.label': 'Override setzen',
    'menu.developer.text_override.clear.label': 'Override loeschen',
    'menu.developer.telemetry.title': 'Entwicklungs-Telemetrie',
    'menu.debug.title': 'Debug / Info',
    'menu.tools.import.label': 'Importieren',
    'menu.tools.export_code.label': 'Code exportieren',
    'menu.tools.export_json.label': 'JSON exportieren',
});

export function listMenuTextCatalogEntries() {
    return Object.entries(MENU_TEXT_CATALOG).map(([id, text]) => ({ id, text }));
}

export function resolveMenuCatalogText(textId, fallback = '') {
    const normalizedTextId = typeof textId === 'string' ? textId.trim() : '';
    if (!normalizedTextId) return fallback;
    return MENU_TEXT_CATALOG[normalizedTextId] || fallback;
}
