export const MENU_TEXT_CATALOG = Object.freeze({
    'menu.level1.single.label': 'Single Player',
    'menu.level1.multiplayer.label': 'Multiplayer',
    'menu.level1.splitscreen.label': 'Splitscreen',
    'menu.level1.help.title': 'Ebene 1: Session-Typ',
    'menu.level1.help.next': 'Danach: Spielstil waehlen',
    'menu.level2.title': 'Ebene 2: Spielstil waehlen',
    'menu.level2.quick.title': 'Sofort spielen',
    'menu.level2.quick.hint': 'Diese Aktionen starten sofort mit vertrauten oder zufaelligen Einstellungen.',
    'menu.level2.quick_last.label': 'Letzte Einstellungen starten',
    'menu.level2.quick_random.label': 'Zufalls-Map direkt starten',
    'menu.level2.mode.title': 'Konfigurieren',
    'menu.level2.mode.hint': 'Waehle einen Stil. Ebene 3 oeffnet direkt mit passenden Vorgaben.',
    'menu.level2.arcade.label': 'Arcade',
    'menu.level2.fight.label': 'Fight',
    'menu.level2.normal.label': 'Normal',
    'menu.level2.next_to_start.label': 'Setup frei anpassen',
    'menu.level3.title': 'Ebene 3: Match vorbereiten',
    'menu.level3.summary.title': 'Startleiste',
    'menu.level3.map.title': 'Map',
    'menu.level3.vehicle.title': 'Flugzeug',
    'menu.level3.theme.title': 'Look & Anzeige',
    'menu.level3.matchfields.title': 'Match & Regeln',
    'menu.level3.matchfields.hint': 'Der Spielstil kommt aus Ebene 2. Hier stellst du nur Flugmodus und Matchdetails nach.',
    'menu.level3.start.label': 'Starten',
    'menu.level3.open_level4.label': 'Feineinstellungen',
    'menu.level3.reset.label': 'Setup zuruecksetzen',
    'menu.level4.title': 'Ebene 4: Feineinstellungen',
    'menu.level4.reset.label': 'Bereich zuruecksetzen',
    'menu.level4.close.label': 'Schliessen',
    'menu.level4.controls.title': 'Steuerung',
    'menu.level4.controls.reset_keys.label': 'Standard-Tasten wiederherstellen',
    'menu.level4.gameplay.title': 'Match-Feinschliff',
    'menu.level4.advanced_map.title': 'Map-Details',
    'menu.level4.tools.title': 'Profile, Presets und Extras',
    'menu.level4.tools.profile_name.label': 'Profilname',
    'menu.level4.tools.profile_save.label': 'Profil speichern',
    'menu.level4.tools.profile_list.label': 'Gespeicherte Profile',
    'menu.level4.tools.profile_load.label': 'Profil laden',
    'menu.level4.tools.profile_delete.label': 'Profil loeschen',
    'menu.level4.tools.preset_catalog.label': 'Preset Katalog',
    'menu.level4.tools.preset_apply.label': 'Preset anwenden',
    'menu.level4.tools.preset_name.label': 'Neuer Preset-Name',
    'menu.level4.tools.preset_save_open.label': 'Als freies Preset speichern',
    'menu.level4.tools.preset_save_fixed.label': 'Als verbindliches Preset speichern',
    'menu.level4.tools.preset_delete.label': 'Preset loeschen',
    'menu.level4.tools.map_editor.label': '3D Map-Editor oeffnen',
    'menu.level4.tools.vehicle_editor.label': 'Vehicle-Editor oeffnen',
    'menu.level4.tools.open_developer.label': 'Developer-Bereich oeffnen',
    'menu.developer.title': 'Developer',
    'menu.developer.open_debug.label': 'Debug / Info oeffnen',
    'menu.developer.text_override.title': 'Textkatalog-Override',
    'menu.developer.text_override.apply.label': 'Override setzen',
    'menu.developer.text_override.clear.label': 'Override loeschen',
    'menu.developer.telemetry.title': 'Entwicklungs-Telemetrie',
    'menu.debug.title': 'Debug / Info',
    'menu.tools.import.label': 'Importieren',
    'menu.tools.export_code.label': 'Code exportieren',
    'menu.tools.export_json.label': 'JSON exportieren',
});

export function listMenuTextCatalogEntries() {
    return Object.entries(MENU_TEXT_CATALOG).map(([id, text]) => ({ id, text }));
}

export function resolveMenuCatalogText(textId, fallback = '') {
    const normalizedTextId = typeof textId === 'string' ? textId.trim() : '';
    if (!normalizedTextId) return fallback;
    return MENU_TEXT_CATALOG[normalizedTextId] || fallback;
}
